## Comments have two # in front of them and commented code has a single #

version: '3.1'
services:
    # server:
    #     build: 
    #         context: .
    #         dockerfile: ./server/dev.Dockerfile
    #     image: wendy-server
    #     ports:
    #         - '3003:3003' #Connect localhost 3003 to container port 3003
    #     links: # Link services to access http://app and http://api inside container
    #         - api:api
    #         - app:app
    # app:
    #     build: 
    #         context: .
    #         dockerfile: ./frontend/dev.Dockerfile
    #     image: wendy-frontend
    #     environment:
    #         - CHOKIDAR_USEPOLLING=true
    #         - NODE_ENV=development
    #         # CI=true is a fix to keep the container running found here: https://github.com/facebook/create-react-app/issues/8688#issuecomment-602110747
    #         - CI=true
    #     volumes: # For webpack dev server to use local files
    #         - ./frontend:/app
    #         - ./frontend/app/node_modules
    #     ports:
    #         - 3000:3000 # For docker to now where to redirect Hot module replacement (HMR) queries
    # api:
    #     build: 
    #         context: .
    #         dockerfile: ./backend/dev.Dockerfile
    #     image: wendy-api
    #     env_file: ./database/database.env
    #     environment: 
    #         - DB_NAME=${APP_MONGO_DB}
    #         - DB_USER=${APP_MONGO_USER}
    #         - DB_PASSWORD=${APP_MONGO_PASS}
    #         - DB_HOST=${MONGO_HOST}
    #         - DB_PORT=${MONGO_PORT}
    #         - NODE_ENV=development
    #     links:
    #         - mongodb:mongodb
    #     volumes: 
    #         - ./backend:/app
    #     ports:
    #         - 3001:3001
    #     depends_on: 
    #        - mongodb
    mongodb:
        image: wendy-database
        build: 
            context: .
            dockerfile: ./database/dev.Dockerfile
        env_file: ./database/database.env
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
            - APP_MONGO_HOST=${MONGO_HOST}
            - MONGO_PORT=${MONGO_PORT}
            - MONGO_ROOT_USER=${MONGO_ROOT_USERNAME}
            - MONGO_ROOT_PASS=${MONGO_ROOT_PASSWORD}
            - APP_MONGO_USER=${APP_MONGO_USER}
            - APP_MONGO_PASS=${APP_MONGO_PASS}
            - APP_MONGO_DB=${APP_MONGO_DB}
        volumes:
            # - ./database/db:/data/db

            ## This script is .sh extension
            - ./database/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
            
            ## This script is .js extension
            ## The current issue with the .js init script is losing to ability to utilize .env values. 
            ## Which makes it nearly impossible to have hidden passwords 
            ## Currently an issue exist to address this: https://github.com/docker-library/mongo/issues/257
            # - ./database/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

        ports:
            - 3002:3002